version: "3.4"
services:

  crawler:
    build: https://github.com/ZeroBrowser/Headless-Crawler.git#main
    networks:
      my_network:
        aliases:
          - crawler
    expose:
      - "5010"
      - "44326"
    ports:
      - "5010:5010"
      - "44326:44326"
    environment:
      - ASPNETCORE_URLS=http://+:5010;https://+:44326
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=green
      - ASPNETCORE_HTTPS_PORT=44326
    volumes:
      - ./:/https:ro

  react:
    build:
      context: ./my-app-typescript
      dockerfile: Dockerfile
    restart: always
    networks:
      my_network:
        aliases:
          - react
    expose:
      - "8080"
      - "80"
    ports:
      - "8080:80"

networks:
  my_network: {}
